import pandas as p
from pandas.tseries.holiday import USFederalHolidayCalendar #US government holidays...
from pandas.tseries.offsets import CustomBusinessDay #CustomBusinessDay is the DateOffset subclass representing custom business days excluding holidays

                                                                   # USA based Calender...        
data = p.read_csv(r'C:\Users\abc\Desktop\Exel\timeseries3.csv')
holiday = CustomBusinessDay(calendar=USFederalHolidayCalendar())

#Before providing holiday...
range_1 = p.date_range(start='07/03/2023',end='12/19/2023',freq='B') # In this daterange 4th jul is a holiday in USA so it can't be consider by freq='B'.Hence we need to import USholiday calender...
#After providing holiday...
range = p.date_range(start='06/20/2023',end='12/21/2023',freq=holiday)# After this thw 4th jul was not printed on the screen... 
data.set_index(range,inplace=True)
print(data)

                                                                  # Egypt Country based Calender...
        
# Based on the Egyptian calender Sun-Thu is working day Fri-Sat is Holiday...

eygpt = CustomBusinessDay(weekmask = 'Sun Mon Tue Wed Thu',holidays=['2023-12-13'])# holiday is used to declare a date as holiday and weekmask is used to assign day of the week...
ranges = p.date_range(start='06/20/2023',end='12/17/2023',freq=eygpt)
data.set_index(ranges,inplace=True)
print(data)