import pandas as p
import numpy as n
                                                                  #to_datetime Function()

data = ['2023/12/1','2023.12.1','20231201' ,'dec 1,2023', '2023-12-1','1/12/2023','balaji'] # As we pass string namely 'balaji', it will commit an error...
print(p.to_datetime(data ,errors='ignore')) #'ignore' is used to ignore the above error...

# To avoid the unwanted string...
print(p.to_datetime(data , errors='coerce'))

# To set our own date format...
date = p.to_datetime('27$8$2004',format='%d$%m$%Y')
print(date)

                                                                    # Period & PeriodIndex
# creating a period index...
index = p.period_range('2015','2023',freq='Q-JAN')# 'Q' means quater...
num = p.Series(n.random.randn(len(index)),index)
print(index)
# converting period index to datetimeindex...
pst = index.to_timestamp()
print(pst)

data = p.read_csv(r'C:\Users\abc\Desktop\Exel\wallmat.csv')
data.set_index('Line Item' , inplace=True)
data = data.T # 'T' is to used to convert row into column and vice versa...
data.index = p.PeriodIndex(data.index , freq='Q-JAN')# converting the object into period index...
data['Start Date'] = data.index.map(lambda x : x.start_time) # map function that works as an iterator to return a result after applying a function to every item of an iterable eg.list,tuple,etc...
data['End Date'] = data.index.map(lambda x : x.start_time)
print(data)
